export const WORLD_CAPITALS = [
  { country: "Afghanistan", city: "Kabul", zone: "Asia/Kabul" },
  { country: "Albania", city: "Tirana", zone: "Europe/Tirane" },
  { country: "Algeria", city: "Algiers", zone: "Africa/Algiers" },
  { country: "Andorra", city: "Andorra la Vella", zone: "Europe/Andorra" },
  { country: "Angola", city: "Luanda", zone: "Africa/Luanda" },
  { country: "Antigua and Barbuda", city: "Saint John's", zone: "America/Antigua" },
  { country: "Argentina", city: "Buenos Aires", zone: "America/Argentina/Buenos_Aires" },
  { country: "Armenia", city: "Yerevan", zone: "Asia/Yerevan" },
  { country: "Australia", city: "Canberra", zone: "Australia/Canberra" },
  { country: "Austria", city: "Vienna", zone: "Europe/Vienna" },
  { country: "Azerbaijan", city: "Baku", zone: "Asia/Baku" },
  { country: "Bahamas", city: "Nassau", zone: "America/Nassau" },
  { country: "Bahrain", city: "Manama", zone: "Asia/Bahrain" },
  { country: "Bangladesh", city: "Dhaka", zone: "Asia/Dhaka" },
  { country: "Barbados", city: "Bridgetown", zone: "America/Barbados" },
  { country: "Belarus", city: "Minsk", zone: "Europe/Minsk" },
  { country: "Belgium", city: "Brussels", zone: "Europe/Brussels" },
  { country: "Belize", city: "Belmopan", zone: "America/Belize" },
  { country: "Benin", city: "Porto-Novo", zone: "Africa/Porto-Novo" },
  { country: "Bhutan", city: "Thimphu", zone: "Asia/Thimphu" },
  { country: "Bolivia", city: "Sucre", zone: "America/La_Paz" },
  { country: "Bosnia and Herzegovina", city: "Sarajevo", zone: "Europe/Sarajevo" },
  { country: "Botswana", city: "Gaborone", zone: "Africa/Gaborone" },
  { country: "Brazil", city: "Brasília", zone: "America/Sao_Paulo" },
  { country: "Brunei", city: "Bandar Seri Begawan", zone: "Asia/Brunei" },
  { country: "Bulgaria", city: "Sofia", zone: "Europe/Sofia" },
  { country: "Burkina Faso", city: "Ouagadougou", zone: "Africa/Ouagadougou" },
  { country: "Burundi", city: "Gitega", zone: "Africa/Bujumbura" },
  { country: "Cambodia", city: "Phnom Penh", zone: "Asia/Phnom_Penh" },
  { country: "Cameroon", city: "Yaoundé", zone: "Africa/Douala" },
  { country: "Canada", city: "Ottawa", zone: "America/Toronto" },
  { country: "Cape Verde", city: "Praia", zone: "Atlantic/Cape_Verde" },
  { country: "Central African Republic", city: "Bangui", zone: "Africa/Bangui" },
  { country: "Chad", city: "N'Djamena", zone: "Africa/Ndjamena" },
  { country: "Chile", city: "Santiago", zone: "America/Santiago" },
  { country: "China", city: "Beijing", zone: "Asia/Shanghai" },
  { country: "Colombia", city: "Bogotá", zone: "America/Bogota" },
  { country: "Comoros", city: "Moroni", zone: "Indian/Comoro" },
  { country: "Congo", city: "Brazzaville", zone: "Africa/Brazzaville" },
  { country: "Costa Rica", city: "San José", zone: "America/Costa_Rica" },
  { country: "Croatia", city: "Zagreb", zone: "Europe/Zagreb" },
  { country: "Cuba", city: "Havana", zone: "America/Havana" },
  { country: "Cyprus", city: "Nicosia", zone: "Asia/Nicosia" },
  { country: "Czech Republic", city: "Prague", zone: "Europe/Prague" },
  { country: "Denmark", city: "Copenhagen", zone: "Europe/Copenhagen" },
  { country: "Djibouti", city: "Djibouti", zone: "Africa/Djibouti" },
  { country: "Dominica", city: "Roseau", zone: "America/Dominica" },
  { country: "Dominican Republic", city: "Santo Domingo", zone: "America/Santo_Domingo" },
  { country: "Ecuador", city: "Quito", zone: "America/Guayaquil" },
  { country: "Egypt", city: "Cairo", zone: "Africa/Cairo" },
  { country: "El Salvador", city: "San Salvador", zone: "America/El_Salvador" },
  { country: "Equatorial Guinea", city: "Malabo", zone: "Africa/Malabo" },
  { country: "Eritrea", city: "Asmara", zone: "Africa/Asmara" },
  { country: "Estonia", city: "Tallinn", zone: "Europe/Tallinn" },
  { country: "Eswatini", city: "Mbabane", zone: "Africa/Mbabane" },
  { country: "Ethiopia", city: "Addis Ababa", zone: "Africa/Addis_Ababa" },
  { country: "Fiji", city: "Suva", zone: "Pacific/Fiji" },
  { country: "Finland", city: "Helsinki", zone: "Europe/Helsinki" },
  { country: "France", city: "Paris", zone: "Europe/Paris" },
  { country: "Gabon", city: "Libreville", zone: "Africa/Libreville" },
  { country: "Gambia", city: "Banjul", zone: "Africa/Banjul" },
  { country: "Georgia", city: "Tbilisi", zone: "Asia/Tbilisi" },
  { country: "Germany", city: "Berlin", zone: "Europe/Berlin" },
  { country: "Ghana", city: "Accra", zone: "Africa/Accra" },
  { country: "Greece", city: "Athens", zone: "Europe/Athens" },
  { country: "Grenada", city: "Saint George's", zone: "America/Grenada" },
  { country: "Guatemala", city: "Guatemala City", zone: "America/Guatemala" },
  { country: "Guinea", city: "Conakry", zone: "Africa/Conakry" },
  { country: "Guinea-Bissau", city: "Bissau", zone: "Africa/Bissau" },
  { country: "Guyana", city: "Georgetown", zone: "America/Guyana" },
  { country: "Haiti", city: "Port-au-Prince", zone: "America/Port-au-Prince" },
  { country: "Honduras", city: "Tegucigalpa", zone: "America/Tegucigalpa" },
  { country: "Hungary", city: "Budapest", zone: "Europe/Budapest" },
  { country: "Iceland", city: "Reykjavik", zone: "Atlantic/Reykjavik" },
  { country: "India", city: "New Delhi", zone: "Asia/Kolkata" },
  { country: "Indonesia", city: "Jakarta", zone: "Asia/Jakarta" },
  { country: "Iran", city: "Tehran", zone: "Asia/Tehran" },
  { country: "Iraq", city: "Baghdad", zone: "Asia/Baghdad" },
  { country: "Ireland", city: "Dublin", zone: "Europe/Dublin" },
  { country: "Israel", city: "Jerusalem", zone: "Asia/Jerusalem" },
  { country: "Italy", city: "Rome", zone: "Europe/Rome" },
  { country: "Jamaica", city: "Kingston", zone: "America/Jamaica" },
  { country: "Japan", city: "Tokyo", zone: "Asia/Tokyo" },
  { country: "Jordan", city: "Amman", zone: "Asia/Amman" },
  { country: "Kazakhstan", city: "Nur-Sultan", zone: "Asia/Almaty" },
  { country: "Kenya", city: "Nairobi", zone: "Africa/Nairobi" },
  { country: "Kiribati", city: "South Tarawa", zone: "Pacific/Tarawa" },
  { country: "Kuwait", city: "Kuwait City", zone: "Asia/Kuwait" },
  { country: "Kyrgyzstan", city: "Bishkek", zone: "Asia/Bishkek" },
  { country: "Laos", city: "Vientiane", zone: "Asia/Vientiane" },
  { country: "Latvia", city: "Riga", zone: "Europe/Riga" },
  { country: "Lebanon", city: "Beirut", zone: "Asia/Beirut" },
  { country: "Lesotho", city: "Maseru", zone: "Africa/Maseru" },
  { country: "Liberia", city: "Monrovia", zone: "Africa/Monrovia" },
  { country: "Libya", city: "Tripoli", zone: "Africa/Tripoli" },
  { country: "Liechtenstein", city: "Vaduz", zone: "Europe/Vaduz" },
  { country: "Lithuania", city: "Vilnius", zone: "Europe/Vilnius" },
  { country: "Luxembourg", city: "Luxembourg", zone: "Europe/Luxembourg" },
  { country: "Madagascar", city: "Antananarivo", zone: "Indian/Antananarivo" },
  { country: "Malawi", city: "Lilongwe", zone: "Africa/Blantyre" },
  { country: "Malaysia", city: "Kuala Lumpur", zone: "Asia/Kuala_Lumpur" },
  { country: "Maldives", city: "Malé", zone: "Indian/Maldives" },
  { country: "Mali", city: "Bamako", zone: "Africa/Bamako" },
  { country: "Malta", city: "Valletta", zone: "Europe/Malta" },
  { country: "Marshall Islands", city: "Majuro", zone: "Pacific/Majuro" },
  { country: "Mauritania", city: "Nouakchott", zone: "Africa/Nouakchott" },
  { country: "Mauritius", city: "Port Louis", zone: "Indian/Mauritius" },
  { country: "Mexico", city: "Mexico City", zone: "America/Mexico_City" },
  { country: "Micronesia", city: "Palikir", zone: "Pacific/Pohnpei" },
  { country: "Moldova", city: "Chisinau", zone: "Europe/Chisinau" },
  { country: "Monaco", city: "Monaco", zone: "Europe/Monaco" },
  { country: "Mongolia", city: "Ulaanbaatar", zone: "Asia/Ulaanbaatar" },
  { country: "Montenegro", city: "Podgorica", zone: "Europe/Podgorica" },
  { country: "Morocco", city: "Rabat", zone: "Africa/Casablanca" },
  { country: "Mozambique", city: "Maputo", zone: "Africa/Maputo" },
  { country: "Myanmar", city: "Naypyidaw", zone: "Asia/Yangon" },
  { country: "Namibia", city: "Windhoek", zone: "Africa/Windhoek" },
  { country: "Nauru", city: "Yaren", zone: "Pacific/Nauru" },
  { country: "Nepal", city: "Kathmandu", zone: "Asia/Kathmandu" },
  { country: "Netherlands", city: "Amsterdam", zone: "Europe/Amsterdam" },
  { country: "New Zealand", city: "Wellington", zone: "Pacific/Auckland" },
  { country: "Nicaragua", city: "Managua", zone: "America/Managua" },
  { country: "Niger", city: "Niamey", zone: "Africa/Niamey" },
  { country: "Nigeria", city: "Abuja", zone: "Africa/Lagos" },
  { country: "North Korea", city: "Pyongyang", zone: "Asia/Pyongyang" },
  { country: "North Macedonia", city: "Skopje", zone: "Europe/Skopje" },
  { country: "Norway", city: "Oslo", zone: "Europe/Oslo" },
  { country: "Oman", city: "Muscat", zone: "Asia/Muscat" },
  { country: "Pakistan", city: "Islamabad", zone: "Asia/Karachi" },
  { country: "Palau", city: "Ngerulmud", zone: "Pacific/Palau" },
  { country: "Panama", city: "Panama City", zone: "America/Panama" },
  { country: "Papua New Guinea", city: "Port Moresby", zone: "Pacific/Port_Moresby" },
  { country: "Paraguay", city: "Asunción", zone: "America/Asuncion" },
  { country: "Peru", city: "Lima", zone: "America/Lima" },
  { country: "Philippines", city: "Manila", zone: "Asia/Manila" },
  { country: "Poland", city: "Warsaw", zone: "Europe/Warsaw" },
  { country: "Portugal", city: "Lisbon", zone: "Europe/Lisbon" },
  { country: "Qatar", city: "Doha", zone: "Asia/Qatar" },
  { country: "Romania", city: "Bucharest", zone: "Europe/Bucharest" },
  { country: "Russia", city: "Moscow", zone: "Europe/Moscow" },
  { country: "Rwanda", city: "Kigali", zone: "Africa/Kigali" },
  { country: "Saint Kitts and Nevis", city: "Basseterre", zone: "America/St_Kitts" },
  { country: "Saint Lucia", city: "Castries", zone: "America/St_Lucia" },
  { country: "Saint Vincent and the Grenadines", city: "Kingstown", zone: "America/St_Vincent" },
  { country: "Samoa", city: "Apia", zone: "Pacific/Apia" },
  { country: "San Marino", city: "San Marino", zone: "Europe/San_Marino" },
  { country: "Saudi Arabia", city: "Riyadh", zone: "Asia/Riyadh" },
  { country: "Senegal", city: "Dakar", zone: "Africa/Dakar" },
  { country: "Serbia", city: "Belgrade", zone: "Europe/Belgrade" },
  { country: "Seychelles", city: "Victoria", zone: "Indian/Mahe" },
  { country: "Sierra Leone", city: "Freetown", zone: "Africa/Freetown" },
  { country: "Singapore", city: "Singapore", zone: "Asia/Singapore" },
  { country: "Slovakia", city: "Bratislava", zone: "Europe/Bratislava" },
  { country: "Slovenia", city: "Ljubljana", zone: "Europe/Ljubljana" },
  { country: "Solomon Islands", city: "Honiara", zone: "Pacific/Guadalcanal" },
  { country: "Somalia", city: "Mogadishu", zone: "Africa/Mogadishu" },
  { country: "South Africa", city: "Pretoria", zone: "Africa/Johannesburg" },
  { country: "South Korea", city: "Seoul", zone: "Asia/Seoul" },
  { country: "South Sudan", city: "Juba", zone: "Africa/Juba" },
  { country: "Spain", city: "Madrid", zone: "Europe/Madrid" },
  { country: "Sri Lanka", city: "Colombo", zone: "Asia/Colombo" },
  { country: "Sudan", city: "Khartoum", zone: "Africa/Khartoum" },
  { country: "Suriname", city: "Paramaribo", zone: "America/Paramaribo" },
  { country: "Sweden", city: "Stockholm", zone: "Europe/Stockholm" },
  { country: "Switzerland", city: "Bern", zone: "Europe/Zurich" },
  { country: "Syria", city: "Damascus", zone: "Asia/Damascus" },
  { country: "Taiwan", city: "Taipei", zone: "Asia/Taipei" },
  { country: "Tajikistan", city: "Dushanbe", zone: "Asia/Dushanbe" },
  { country: "Tanzania", city: "Dodoma", zone: "Africa/Dar_es_Salaam" },
  { country: "Thailand", city: "Bangkok", zone: "Asia/Bangkok" },
  { country: "Timor-Leste", city: "Dili", zone: "Asia/Dili" },
  { country: "Togo", city: "Lomé", zone: "Africa/Lome" },
  { country: "Tonga", city: "Nuku'alofa", zone: "Pacific/Tongatapu" },
  { country: "Trinidad and Tobago", city: "Port of Spain", zone: "America/Port_of_Spain" },
  { country: "Tunisia", city: "Tunis", zone: "Africa/Tunis" },
  { country: "Turkey", city: "Ankara", zone: "Europe/Istanbul" },
  { country: "Turkmenistan", city: "Ashgabat", zone: "Asia/Ashgabat" },
  { country: "Tuvalu", city: "Funafuti", zone: "Pacific/Funafuti" },
  { country: "Uganda", city: "Kampala", zone: "Africa/Kampala" },
  { country: "Ukraine", city: "Kyiv", zone: "Europe/Kyiv" },
  { country: "United Arab Emirates", city: "Abu Dhabi", zone: "Asia/Dubai" },
  { country: "United Kingdom", city: "London", zone: "Europe/London" },
  { country: "United States", city: "Washington, D.C.", zone: "America/New_York" },
  { country: "Uruguay", city: "Montevideo", zone: "America/Montevideo" },
  { country: "Uzbekistan", city: "Tashkent", zone: "Asia/Tashkent" },
  { country: "Vanuatu", city: "Port Vila", zone: "Pacific/Efate" },
  { country: "Vatican City", city: "Vatican City", zone: "Europe/Vatican" },
  { country: "Venezuela", city: "Caracas", zone: "America/Caracas" },
  { country: "Vietnam", city: "Hanoi", zone: "Asia/Ho_Chi_Minh" },
  { country: "Yemen", city: "Sana'a", zone: "Asia/Aden" },
  { country: "Zambia", city: "Lusaka", zone: "Africa/Lusaka" },
  { country: "Zimbabwe", city: "Harare", zone: "Africa/Harare" }
];
